### ISSUE TITLE
Увеличить размер результата вычислений

### ISSUE THREAD

**Issue by MelikbekyanAshot** [std-22/LAMA#2]
Увеличить размер 
![Screenshot_20210219-220538_LAMA 1](https://user-images.githubusercontent.com/41271647/108549987-face0f00-72fe-11eb-9df5-0d347e201e0a.jpg)
![Screenshot_20210219-220511_LAMA 1](https://user-images.githubusercontent.com/41271647/108550031-06b9d100-72ff-11eb-99b4-741897c10c9d.jpg)

**Comment by tolokonov** [comment]
Еще иногда название функции больше, чем пространство выделенное под нее, поэтому оно заползает на стрелку "назад"

**Comment by MelikbekyanAshot** [comment]
Done
